version: '3.8'

services:
  backend:
    build: ./backend
    container_name: farpost-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    container_name: farpost-frontend
    ports:
      - "3000:80"
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped